version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/2025.1-T02-ConsultTributario
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
