### Create claim
POST http://localhost:8000/claims
Content-Type: application/json

{
  "title": "Claim 4",
  "objective": "Objective for claim 1",
  "summary": "Summary for claim 1",
  "recoverable_period": "12 months",
  "recoverable_value": "1000",
  "relatedQuestions": "68365ccfed8b809ccb0c60ce"
}

### Find all claims
GET http://localhost:8000/claims

### Find claim by id
GET http://localhost:8000/claims/683b3cf012fae1a976e73a48

### Delete claim
DELETE http://localhost:8000/claims/683b3cf012fae1a976e73a48