### Create diagnosis
POST http://localhost:8000/diagnoses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJzdWIiOiI2ODU4NmM4ZDc3ODdkMjM5ZTBjNDI1NjAiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjQzNjc5OSwiZXhwIjoxNzUyNTIzMTk5fQ.qUs_OMq2Nu8vtvUedk8FpL3q0FYc9kba_pO2LXJpRF0
Content-Type: application/json

{
  "clientName": "New Diagnosis",
  "questionResponses": [
    {
      "questionId": "683c6de111fb31187f89798f",
      "answer": "dont_know"
    }
  ]
}

### Find all diagnoses
GET http://localhost:8000/diagnoses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwic3ViIjoiNjg1YTBhNDJmYmFmN2FmZjhhMzVhMTIzIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTI0MzcwNjAsImV4cCI6MTc1MjUyMzQ2MH0.tI_4T4XPzjaa9fHsq_jLxfT8FEI7dKNNAuXDaTmgvVc

### Find diagnosis by ID
GET http://localhost:8000/diagnoses/68740dfca288155a4cad38ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwic3ViIjoiNjg1YTBhNDJmYmFmN2FmZjhhMzVhMTIzIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTI0MzcwNjAsImV4cCI6MTc1MjUyMzQ2MH0.tI_4T4XPzjaa9fHsq_jLxfT8FEI7dKNNAuXDaTmgvVc

### Find diagnosis recommended by ID
GET http://localhost:8000/diagnoses/68740dfca288155a4cad38ba/recommendations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGV4YW1wbGUuY29tIiwic3ViIjoiNjg1YTBhNDJmYmFmN2FmZjhhMzVhMTIzIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NTI0MzcwNjAsImV4cCI6MTc1MjUyMzQ2MH0.tI_4T4XPzjaa9fHsq_jLxfT8FEI7dKNNAuXDaTmgvVc